Fix non zero exit status
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Finished running ram share association for application: mlra
Error: Process completed with exit code 1.
```

I can't work out what is causing the exit code to be one, explicitly exiting
successful functions with zero to see if this helps