Add VPCs that sit within the core vpc sandbox account (#1283)
* Add VPCs that sit within the core vpc sandbox account

* Commit changes made by code formatters

* PASS - Environment files check
FAILED - Extra of missing environments-network/*.json files
Diff:
		cica-development
garden-development
	garden-sandbox
		hmcts-development
		hmcts-production
		hmpps-development
		hmpps-preproduction
		hmpps-production
		hmpps-test
house-development
	house-sandbox
		platforms-development
		platforms-test
Error: Process completed with exit code 1.

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>