Add missing sandbox role to member ci
The sprinker workflow was failing with:

```
Error: error configuring Terraform AWS Provider: IAM Role (arn:aws:iam::xxxxxxx:role/member-delegation-garden-sandbox) cannot be assumed.
```

This adds the missing resource to the allow statement