Fix ram sharing running when it shouldn't
'''
Environment: production
Account: mlra-preproduction
Running terraform across workspace mlra-preproduction-production
Terraform init
Error handling -chdir option: chdir terraform/environments/mlra-preproduction: no such file or directory
Error: Process completed with exit code 1.
'''

RAM sharing was running for accounts it shouldn't, eg above it's running
in production for a preproduction account.  This is because the list of
changed accounts isn't being filter.  The new grep checks and filters
out any accounts which don't match the environment.

Also fixing spelling errors.