Fix equip SES user policy
The workflow was failing with:

```
Error: Missing required argument
  on iam.tf line 12, in resource "aws_iam_user_policy" "email_policy":
  12: resource "aws_iam_user_policy" "email_policy" {
The argument "policy" is required, but no definition was found.
```

Added the policy to match the exising inline policy and imported it into
terraform, ran apply and no changes are required in production.