Remove access key creation
We want users to be able to create and rotate their own access keys.  If
we create on for them there is a scenario where they delete this key,
and create 2 more keys, this TF then fails with:

```
Error: Error creating access key for user cicd-member-user: LimitExceeded: Cannot exceed quota for AccessKeysPerUser: 2
```

Users can create their own key so we don't really need this default one
here.