Allow member-ci user to iam:ListAccountAliases. Related error:
Switched to workspace "sprinkler-development".
Error: failed get account alias: AccessDenied: User: arn:aws:iam::946070829339:user/member-ci is not authorized to perform: iam:ListAccountAliases on resource: *
	status code: 403, request id: 57ff0700-601c-4471-bcc2-002773ad5e73
Error: Process completed with exit code 255.