Fix image_uri issue. (#2419)
* Fix image_uri issue.

Plan: 4 to add, 0 to change, 0 to destroy.
aws_iam_role.instance-scheduler-lambda-function: Creating...

Error: error creating Lambda Function (1): InvalidParameterValueException: Source image instance-scheduler-ecr-repo:latest is not valid. Provide a valid source image.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "a1f03d5c-f72b-4e7e-a923-7858e8970475"
  },
  Message_: "Source image instance-scheduler-ecr-repo:latest is not valid. Provide a valid source image.",
  Type: "User"
}

* ID aws-iam-no-policy-wildcards
      Impact Overly permissive policies may grant access to sensitive resources
  Resolution Specify the exact permissions required, and to which resources they should apply instead of using wildcards.

  More Information
  - https://aquasecurity.github.io/tfsec/latest/checks/aws/iam/no-policy-wildcards/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document